name: Check App Test

on: [pull_request]

jobs:
  test:
    name: Check test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ecommerce
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.5
      - name: Make execute
        run: chmod +x ./gradlew
      - name: init with Gradle
        uses: gradle/gradle-build-action@v2
      - run: gradle init
      - run: ./gradlew test